/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-sci-fi-vehicle-012-03-public-domain-cc0-aa1c88740d924f8c8e60b15c69f47b57
title: FREE Sci-Fi Vehicle 012 03 - public domain (CC0)
*/

import  { useLayoutEffect, useRef } from "react";
import { OrbitControls, useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { gsap } from "gsap";


export function Model(props) {
  const { nodes, materials } = useGLTF("/models/scifi.glb")

  const scrollControl = useScroll()
  const timeline = useRef()

  useLayoutEffect(()=>{
    timeline.current = gsap.timeline()
  },[])


  useFrame(()=>{ })

  return (
    <>
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_Material_0.geometry}
                  material={materials.Material}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube001_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube002_Material002_0.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube004_taillights_0.geometry}
                  material={materials.taillights}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube015_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube016_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube017_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube018_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube019_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube020_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube021_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                position={[0, 0, 57.4]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={621.41}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.SFV_011_02_shadow001_SFV_011_03_shadow_0.geometry
                  }
                  material={materials.SFV_011_03_shadow}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube025_Material_0.geometry}
                  material={materials.Material}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube026_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube027_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube028_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube034_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube035_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube036_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube037_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube038_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube039_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube040_headlights_0.geometry}
                  material={materials.headlights}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
        <OrbitControls />
    </>
  );
}

useGLTF.preload("/models/scifi.glb");
